# coding: utf-8

"""
    VRM API

    ## Introduction This document provides a brief overview of some of the available endpoints and their parameters. The API is a REST API, accepting JSON as request body. You can use the try-it tool to play around with it, or use software like Postman.  ## Authentication Most endpoints require authentication, using a JWT token. This token should be placed in the `x-authorization` field in the HTTP header. There are two types of tokens. - Bearer token. Uses the `Bearer <token_value>` format. This is used when logging in to VRM, for example. Can be retrieved from [/auth/login](/operations/auth/login) or [/auth/loginAsDemo](/operations/auth/loginAsDemo). - Access token. Uses the `Token <token_value>` format. This is commonly used for third party applications using the VRM API. Can be created using [/users/{idUser}/accesstokens/create](/operations/users/idUser/accesstokens/create).  ## Rate limiting Most endpoints are by default rate limited with a rolling window of max 200 requests, where every 0.33 seconds a request gets removed from the rolling window. (so on average maximum of 3 requests per second won't get rate limited). There are different types of ratelimiting in VRM. If you receive a 429 with a JSON response, you can check the Retry-After response header to check the amount of seconds you have to wait until retrying.  ## WARNING & DISCLAIMER Whilst publicly available, Victron Energy does not offer support to professional customers or end-users that implement features using the here documented functionality, except in really specific situations (i.e such as a special arrangement with a large OEM customer).  The recommended method for support on the VRM API is to use the Modifications section on Victron Community. This space is frequently visited by many people using the API, and other methods of integrating with Victron products. Direct company support is only offered on a limited basis via your Victron representative.  # noqa: E501

    OpenAPI spec version: 2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AuthLoginBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'username': 'object',
        'password': 'object',
        'sms_token': 'object',
        'remember_me': 'object'
    }

    attribute_map = {
        'username': 'username',
        'password': 'password',
        'sms_token': 'sms_token',
        'remember_me': 'remember_me'
    }

    def __init__(self, username=None, password=None, sms_token=None, remember_me=None):  # noqa: E501
        """AuthLoginBody - a model defined in Swagger"""  # noqa: E501
        self._username = None
        self._password = None
        self._sms_token = None
        self._remember_me = None
        self.discriminator = None
        self.username = username
        self.password = password
        if sms_token is not None:
            self.sms_token = sms_token
        if remember_me is not None:
            self.remember_me = remember_me

    @property
    def username(self):
        """Gets the username of this AuthLoginBody.  # noqa: E501

        User e-mail  # noqa: E501

        :return: The username of this AuthLoginBody.  # noqa: E501
        :rtype: object
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this AuthLoginBody.

        User e-mail  # noqa: E501

        :param username: The username of this AuthLoginBody.  # noqa: E501
        :type: object
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def password(self):
        """Gets the password of this AuthLoginBody.  # noqa: E501

        User password  # noqa: E501

        :return: The password of this AuthLoginBody.  # noqa: E501
        :rtype: object
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this AuthLoginBody.

        User password  # noqa: E501

        :param password: The password of this AuthLoginBody.  # noqa: E501
        :type: object
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def sms_token(self):
        """Gets the sms_token of this AuthLoginBody.  # noqa: E501

        2FA code (if 2FA is enabled for the user)  # noqa: E501

        :return: The sms_token of this AuthLoginBody.  # noqa: E501
        :rtype: object
        """
        return self._sms_token

    @sms_token.setter
    def sms_token(self, sms_token):
        """Sets the sms_token of this AuthLoginBody.

        2FA code (if 2FA is enabled for the user)  # noqa: E501

        :param sms_token: The sms_token of this AuthLoginBody.  # noqa: E501
        :type: object
        """

        self._sms_token = sms_token

    @property
    def remember_me(self):
        """Gets the remember_me of this AuthLoginBody.  # noqa: E501

        Get a long-lived token which stays valid for longer  # noqa: E501

        :return: The remember_me of this AuthLoginBody.  # noqa: E501
        :rtype: object
        """
        return self._remember_me

    @remember_me.setter
    def remember_me(self, remember_me):
        """Sets the remember_me of this AuthLoginBody.

        Get a long-lived token which stays valid for longer  # noqa: E501

        :param remember_me: The remember_me of this AuthLoginBody.  # noqa: E501
        :type: object
        """

        self._remember_me = remember_me

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AuthLoginBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuthLoginBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
